language: java
jdk:
  - oraclejdk11
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: constitulinguo
script:
  - mvn clean package -Dspring.active.profiles=prod -Dmongo_user=$mongo_user -Dmongo_pass=$mongo_pass -Dmongo_host=$mongo_host -Dmongo_port=$mongo_port
